version: '3.8'

services:
  bot:
    build: .
    container_name: wetero_bot
    restart: always
    volumes:
      - ./data:/app/data
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - TZ=Europe/Moscow
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
